---

vxlan:
  fabric:
    name: msd-fabric-group
    type: MSD
  multisite:
    anycast_gateway_mac: 1234.5678.9000
    overlay_dci:
      deployment_method: Centralized_To_Route_Server
      route_server:
        redistribute_direct: true
        ip_tag: 54321
        peers:
          - ip_address: 10.101.101.101
            bgp_asn: "65101"
          - ip_address: 10.201.201.201
            bgp_asn: "65201"
      underlay_autoconfig: true
      enable_bgp_send_community: true
