# ---
# 
# vxlan:
#   overlay:
#     vrfs:
#       - name: NaC-VRF01
#         vrf_id: 200001
#         vlan_id: 2001
#         vrf_attach_group: all
#     vrf_attach_groups:
#       - name: all
#         switches:
#           - hostname: site1-l1
#           - hostname: site1-l2
#           - hostname: site1-bl1
